[project]
name = "ner-landslide-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.3",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "joblib>=1.6.0",
    "numpy>=2.4.6",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.9.1",
    "sqlalchemy>=2.0.52",
    "twilio>=9.11.1",
    "uvicorn[standard]>=0.52.4",
]
